title: My Tech Blog
description: A blog about the latest in technology.
theme: minima
baseurl: "https://marcosvandrade.github.io/"
url: "https://marcosvandrade.github.io/my-tech-blog/"
markdown: kramdown
